---
abstract: 'Perl interface to cvs.'
author:
  - 'Stephen Cardie <stephenca@ls26.net>'
build_requires:
  Cwd: 0
  Directory::Scratch: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  Test::More: 0
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cvs-Simple
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Cvs::Simple:
    file: lib/Cvs/Simple.pm
    version: 0.07_03
  Cvs::Simple::Hook:
    file: lib/Cvs/Simple/Hook.pm
    version: 0.07_03
requires:
  Carp: 0
  Class::Std::Utils: 0
  File::Which: 0
  IO::Lines: 0
  IO::Pipe: 0
  Module::Runtime: 0
  Scalar::Util: 0
  Try::Tiny: 0
  common::sense: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Cvs-Simple
version: 0.07_03
