# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cvs-Simple
version:      0.03
version_from: lib/Cvs/Simple.pm
installdirs:  site
requires:
    Class::Std::Utils              0
    Scalar::Util                   0 
    File::Copy:                    0
    Test::Pod:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
