#!/usr/bin/perl
# Auto-generated by Makefile.PL
package Cvs::Simple::Config;
use strict;
use warnings;

sub CVS_BIN  () { '/usr/bin/cvs_real' }
sub EXTERNAL () { ':ext:stephenca@vhost.ls26.net:/var/lib/cvs' }

1;
